[project]
name = "tea-disease-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.3.0",
    "faker>=40.1.0",
    "matplotlib",
    "numpy",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "pycocotools",
    "pyqt6",
    "qdrant-client>=1.16.2",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "thop>=0.1.1.post2209072238",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]

[tool.uv.workspace]
members = [
    "backend",
]
